# Generated by Django 4.1.3 on 2022-11-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('ClassID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Term', models.CharField(max_length=50)),
                ('Year', models.BigIntegerField()),
                ('Instructor', models.CharField(max_length=50)),
                ('Classroom', models.CharField(max_length=50)),
                ('ClassTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDesc', models.TextField()),
                ('Credits', models.IntegerField()),
                ('DeptID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gradevalue',
            fields=[
                ('Grade', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('QGrade', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('Addr1', models.TextField()),
                ('Addr2', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('StateProvince', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=50)),
                ('PostalCode', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stuclasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classe')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gradevalue')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
